src/Entity/Customers.php
<?php

namespace App\Entity;

use App\Repository\CustomersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: CustomersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Customers implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();
        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('');
    }

    #[Route(path: '/', name: 'main')]
    public function main(): Response
    {
        return $this->redirectToRoute('shop');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Вхід в акаунт{% endblock %}

{% block body %}
    <div class="p-10 w-full md:w-3/6 container">
        <h1 class="mb-4 mt-20 font-extrabold text-4xl">Вхід в акаунт</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
            <form method="post">
                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}
                {% if app.user %}
                    <div class="mb-3">
                        You are logged in as {{ app.user.userIdentifier }}, <a
                                href="{{ path('app_logout') }}">Logout</a>
                    </div>
                {% endif %}
                <div>
                    <div class="mb-4">
                        <label class="" for="inputEmail">Пошта</label>
                        <input class="w-full shadow-inner bg-gray-100 rounded-lg placeholder-black text-1xl p-3 border-none block mt-2"
                               type="email" value="{{ last_username }}" name="email" id="inputEmail"
                               autocomplete="email" required autofocus>
                    </div>

                    <div class="mb-4">
                        <label for="inputPassword">Пароль</label>
                        <input class="w-full shadow-inner bg-gray-100 rounded-lg placeholder-black text-1xl p-3 border-none block mt-2"
                               type="password" name="password" id="inputPassword" autocomplete="current-password"
                               required>
                    </div>

                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >

                    <div class="flex items-center justify-between mt-8">
                        <button type="submit" class="mb-2 px-2.5 py-1.5 rounded-md text-white bg-indigo-500">Увійти
                        </button>
                    </div>
                </div>
            </form>
            <div class="bg-gray-100 p-8 rounded">
                <h2 class="font-bold text-2xl">Важлива інформація</h2>
                <ul class="list-disc mt-2 list-inside">
                    <li class="mb-3">Ваші персональні дані не будуть передаватись третім особам.</li>
                    <li class="mb-3">Заповніть дані уважно щоб при замовленні товару ми змогли зв'язатись з вами.</li>
                    <li class="mb-3">Якщо у вас з'являюсться питання ви можете звернутись до нашої технічної
                        підтримки.
                    </li>
                </ul>
                <div class="text-center">
                    <a href="/register" class="text-gray-500 hover:text-gray-900">Зареєструватися</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}