src/Entity/Reviews.php
<?php

namespace App\Entity;

use App\Repository\ReviewsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReviewsRepository::class)]
class Reviews
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Processor $processor = null;

    #[ORM\ManyToOne(inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customers $customer = null;

    #[ORM\Column]
    private ?int $rating = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProcessor(): ?Processor
    {
        return $this->processor;
    }

    public function setProcessor(?Processor $processor): static
    {
        $this->processor = $processor;

        return $this;
    }

    public function getCustomer(): ?Customers
    {
        return $this->customer;
    }

    public function setCustomer(?Customers $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/product_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ processor.name }}{% endblock %}

{% block body %}
    <div class="dark:bg-gray-800 py-8">
        <div class="mt-20 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col md:flex-row -mx-4">
                <div class="md:flex-1 px-4">
                    {% if processor.image %}
                        <div class="h-[460px] rounded-lg overflow-hidden mb-4">
                            <img class="w-full h-full object-cover" src="{{ asset('images/' ~ processor.image) }}"
                                 alt="{{ processor.name }} Image">
                        </div>
                    {% endif %}
                </div>
                <div class="md:flex-1 px-4">
                    <h2 class="text-2xl font-bold text-gray-800 dark:text-white mb-2">{{ processor.name }}</h2>
                    <p class="text-gray-600 dark:text-gray-300 text-sm mb-4">
                        Бренд: {{ processor.brand.name }}<br>
                        Тип роз'єму: {{ processor.socketType.name }}<br>
                        Кількість ядер: {{ processor.cores }}<br>
                        Кількість потоків: {{ processor.threads }}<br>
                        Тактова частота: {{ processor.baseClockSpeed }} ГГц - {{ processor.maxClockSpeed }} ГГц<br>
                        Техпроцес: {{ processor.techProcess }} нм<br>
                        Потужність TDP: {{ processor.tdp }}<br>
                        Обсяг кеш пам'яті: {{ processor.cacheMemory }} МБ<br>
                        Інтегрована графіка: {{ processor.integratedGraphics.name }}<br>
                        Ціна: {{ processor.price }} грн
                    </p>
                    <div>
                        <span class="font-bold text-gray-700 dark:text-gray-300">Опис процесора</span>
                        <p class="text-gray-600 dark:text-gray-300 text-sm mt-2">
                            {{ processor.description }}
                        </p>
                        <div class="w-1/2 mt-4">
                            <a href="{{ path('add_to_cart', {'id': processor.id}) }}"
                               class="w-full bg-green-500 text-white py-2 px-4 rounded-md font-bold hover:bg-green-600">Додати
                                до кошика</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="p-6 md:w-1/2">
                <h2 class="text-lg font-bold mb-4">{% if isReviewExist %}Редагувати відгук{% else %}Залишити відгук{% endif %}</h2>
                <div class="flex flex-col space-y-4">

                    {{ form(form) }}
                    {% if reviews|length != 0 %}
                        {% for review in reviews %}
                            <div class="bg-white p-4 rounded-lg shadow-md">
                                <h2 class="text-xl font-bold">
                                    {% for _ in 1..review.rating %}
                                        <i class="fi-rr-star text-yellow-400"></i>
                                    {% endfor %}
                                </h2>
                                <h3 class="text-lg font-bold">{{ review.customer.name }}</h3>
                                <p class="text-gray-700 text-sm mb-2">{{ review.createdAt|date('Y-m-d H:i:s') }}</p>
                                <p class="text-gray-700">{{ review.comment }}</p>
                            </div>
                            <hr class="my-4">
                        {% endfor %}
                    {% else %}
                        <div class="bg-white p-4 rounded-lg shadow-md">
                            <h2 class="text-xl font-bold">Відгуки поки відсутні. Додавайте першими!</h2>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}